/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";
import type { IPostgresInterval } from "postgres-interval";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Interval = ColumnType<IPostgresInterval, IPostgresInterval | number | string, IPostgresInterval | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _TimescaledbCatalogChunk {
  compressedChunkId: number | null;
  creationTime: Timestamp;
  dropped: Generated<boolean>;
  hypertableId: number;
  id: Generated<number>;
  osmChunk: Generated<boolean>;
  schemaName: string;
  status: Generated<number>;
  tableName: string;
}

export interface _TimescaledbCatalogChunkColumnStats {
  chunkId: number;
  columnName: string;
  hypertableId: number;
  id: Generated<number>;
  rangeEnd: Int8;
  rangeStart: Int8;
  valid: boolean;
}

export interface _TimescaledbCatalogChunkConstraint {
  chunkId: number;
  constraintName: string;
  dimensionSliceId: number | null;
  hypertableConstraintName: string | null;
}

export interface _TimescaledbCatalogChunkIndex {
  chunkId: number;
  hypertableId: number;
  hypertableIndexName: string;
  indexName: string;
}

export interface _TimescaledbCatalogCompressionAlgorithm {
  description: string | null;
  id: number;
  name: string;
  version: number;
}

export interface _TimescaledbCatalogCompressionChunkSize {
  chunkId: number;
  compressedChunkId: number;
  compressedHeapSize: Int8;
  compressedIndexSize: Int8;
  compressedToastSize: Int8;
  numrowsFrozenImmediately: Int8 | null;
  numrowsPostCompression: Int8 | null;
  numrowsPreCompression: Int8 | null;
  uncompressedHeapSize: Int8;
  uncompressedIndexSize: Int8;
  uncompressedToastSize: Int8;
}

export interface _TimescaledbCatalogCompressionSettings {
  compressRelid: string | null;
  orderby: string[] | null;
  orderbyDesc: boolean[] | null;
  orderbyNullsfirst: boolean[] | null;
  relid: string;
  segmentby: string[] | null;
}

export interface _TimescaledbCatalogContinuousAgg {
  directViewName: string;
  directViewSchema: string;
  finalized: Generated<boolean>;
  materializedOnly: Generated<boolean>;
  matHypertableId: number;
  parentMatHypertableId: number | null;
  partialViewName: string;
  partialViewSchema: string;
  rawHypertableId: number;
  userViewName: string;
  userViewSchema: string;
}

export interface _TimescaledbCatalogContinuousAggMigratePlan {
  endTs: Timestamp | null;
  matHypertableId: number;
  startTs: Generated<Timestamp>;
  userViewDefinition: string | null;
}

export interface _TimescaledbCatalogContinuousAggMigratePlanStep {
  config: Json | null;
  endTs: Timestamp | null;
  matHypertableId: number;
  startTs: Timestamp | null;
  status: Generated<string>;
  stepId: Generated<number>;
  type: string;
}

export interface _TimescaledbCatalogContinuousAggsBucketFunction {
  bucketFixedWidth: boolean;
  bucketFunc: string;
  bucketOffset: string | null;
  bucketOrigin: string | null;
  bucketTimezone: string | null;
  bucketWidth: string;
  matHypertableId: number;
}

export interface _TimescaledbCatalogContinuousAggsHypertableInvalidationLog {
  greatestModifiedValue: Int8;
  hypertableId: number;
  lowestModifiedValue: Int8;
}

export interface _TimescaledbCatalogContinuousAggsInvalidationThreshold {
  hypertableId: number;
  watermark: Int8;
}

export interface _TimescaledbCatalogContinuousAggsMaterializationInvalidationLog {
  greatestModifiedValue: Int8;
  lowestModifiedValue: Int8;
  materializationId: number | null;
}

export interface _TimescaledbCatalogContinuousAggsWatermark {
  matHypertableId: number;
  watermark: Int8;
}

export interface _TimescaledbCatalogDimension {
  aligned: boolean;
  columnName: string;
  columnType: string;
  compressIntervalLength: Int8 | null;
  hypertableId: number;
  id: Generated<number>;
  integerNowFunc: string | null;
  integerNowFuncSchema: string | null;
  intervalLength: Int8 | null;
  numSlices: number | null;
  partitioningFunc: string | null;
  partitioningFuncSchema: string | null;
}

export interface _TimescaledbCatalogDimensionSlice {
  dimensionId: number;
  id: Generated<number>;
  rangeEnd: Int8;
  rangeStart: Int8;
}

export interface _TimescaledbCatalogHypertable {
  associatedSchemaName: string;
  associatedTablePrefix: string;
  chunkSizingFuncName: string;
  chunkSizingFuncSchema: string;
  chunkTargetSize: Int8;
  compressedHypertableId: number | null;
  compressionState: Generated<number>;
  id: Generated<number>;
  numDimensions: number;
  schemaName: string;
  status: Generated<number>;
  tableName: string;
}

export interface _TimescaledbCatalogMetadata {
  includeInTelemetry: boolean;
  key: string;
  value: string;
}

export interface _TimescaledbCatalogTablespace {
  hypertableId: number;
  id: Generated<number>;
  tablespaceName: string;
}

export interface _TimescaledbCatalogTelemetryEvent {
  body: Json;
  created: Generated<Timestamp>;
  tag: string;
}

export interface _TimescaledbConfigBgwJob {
  applicationName: string;
  checkName: string | null;
  checkSchema: string | null;
  config: Json | null;
  fixedSchedule: Generated<boolean>;
  hypertableId: number | null;
  id: Generated<number>;
  initialStart: Timestamp | null;
  maxRetries: number;
  maxRuntime: Interval;
  owner: Generated<string>;
  procName: string;
  procSchema: string;
  retryPeriod: Interval;
  scheduled: Generated<boolean>;
  scheduleInterval: Interval;
  timezone: string | null;
}

export interface _TimescaledbInternalBgwJobStat {
  consecutiveCrashes: number;
  consecutiveFailures: number;
  flags: Generated<number>;
  jobId: number;
  lastFinish: Timestamp;
  lastRunSuccess: boolean;
  lastStart: Generated<Timestamp>;
  lastSuccessfulFinish: Timestamp;
  nextStart: Timestamp;
  totalCrashes: Int8;
  totalDuration: Interval;
  totalDurationFailures: Interval;
  totalFailures: Int8;
  totalRuns: Int8;
  totalSuccesses: Int8;
}

export interface _TimescaledbInternalBgwJobStatHistory {
  data: Json | null;
  executionFinish: Timestamp | null;
  executionStart: Generated<Timestamp>;
  id: Generated<Int8>;
  jobId: number;
  pid: number | null;
  succeeded: boolean | null;
}

export interface _TimescaledbInternalBgwPolicyChunkStats {
  chunkId: number;
  jobId: number;
  lastTimeJobRun: Timestamp | null;
  numTimesJobRun: number | null;
}

export interface _TimescaledbInternalCompressedChunkStats {
  chunkName: string | null;
  chunkSchema: string | null;
  compressedHeapSize: Int8 | null;
  compressedIndexSize: Int8 | null;
  compressedToastSize: Int8 | null;
  compressedTotalSize: Int8 | null;
  compressionStatus: string | null;
  hypertableName: string | null;
  hypertableSchema: string | null;
  uncompressedHeapSize: Int8 | null;
  uncompressedIndexSize: Int8 | null;
  uncompressedToastSize: Int8 | null;
  uncompressedTotalSize: Int8 | null;
}

export interface _TimescaledbInternalHypertableChunkLocalSize {
  chunkId: number | null;
  chunkName: string | null;
  chunkSchema: string | null;
  compressedHeapSize: Int8 | null;
  compressedIndexSize: Int8 | null;
  compressedToastSize: Int8 | null;
  compressedTotalSize: Int8 | null;
  heapBytes: Int8 | null;
  hypertableId: number | null;
  hypertableName: string | null;
  hypertableSchema: string | null;
  indexBytes: Int8 | null;
  toastBytes: Int8 | null;
  totalBytes: Int8 | null;
}

export interface BondingCurve {
  coinMetadata: string;
  id: string;
  issuer: string;
  migrationTarget: string;
  treasuryCap: string;
}

export interface Coins {
  address: string;
  createdAt: Generated<Timestamp>;
  description: string;
  id: string;
  logo: string;
  name: string;
  symbol: string;
}

export interface Comments {
  content: string;
  createdAt: Timestamp;
  id: Generated<Int8>;
  postId: Int8;
  userId: string;
}

export interface Cursors {
  eventSeq: string;
  id: string;
  txDigest: string;
}

export interface Images {
  imageName: string;
  imagePath: string;
  postId: Generated<Int8>;
}

export interface Likes {
  createdAt: Timestamp;
  id: Generated<Int8>;
  postId: Int8;
  userId: string;
}

export interface Posts {
  coinId: string | null;
  content: string;
  createdAt: Timestamp;
  id: Generated<Int8>;
  mediaUrls: string[] | null;
  userId: string;
}

export interface RawPrices {
  amountIn: number;
  amountOut: number;
  bondingCurveId: string;
  direction: string;
  price: number;
  sender: string;
  timestamp: Timestamp;
}

export interface TimescaledbExperimentalPolicies {
  config: Json | null;
  hypertableName: string | null;
  hypertableSchema: string | null;
  procName: string | null;
  procSchema: string | null;
  relationName: string | null;
  relationSchema: string | null;
  scheduleInterval: Interval | null;
}

export interface TimescaledbInformationChunkColumnstoreSettings {
  chunk: string | null;
  hypertable: string | null;
  orderby: string | null;
  segmentby: string | null;
}

export interface TimescaledbInformationChunkCompressionSettings {
  chunk: string | null;
  hypertable: string | null;
  orderby: string | null;
  segmentby: string | null;
}

export interface TimescaledbInformationChunks {
  chunkCreationTime: Timestamp | null;
  chunkName: string | null;
  chunkSchema: string | null;
  chunkTablespace: string | null;
  hypertableName: string | null;
  hypertableSchema: string | null;
  isCompressed: boolean | null;
  primaryDimension: string | null;
  primaryDimensionType: string | null;
  rangeEnd: Timestamp | null;
  rangeEndInteger: Int8 | null;
  rangeStart: Timestamp | null;
  rangeStartInteger: Int8 | null;
}

export interface TimescaledbInformationCompressionSettings {
  attname: string | null;
  hypertableName: string | null;
  hypertableSchema: string | null;
  orderbyAsc: boolean | null;
  orderbyColumnIndex: number | null;
  orderbyNullsfirst: boolean | null;
  segmentbyColumnIndex: number | null;
}

export interface TimescaledbInformationContinuousAggregates {
  compressionEnabled: boolean | null;
  finalized: boolean | null;
  hypertableName: string | null;
  hypertableSchema: string | null;
  materializationHypertableName: string | null;
  materializationHypertableSchema: string | null;
  materializedOnly: boolean | null;
  viewDefinition: string | null;
  viewName: string | null;
  viewOwner: string | null;
  viewSchema: string | null;
}

export interface TimescaledbInformationDimensions {
  columnName: string | null;
  columnType: string | null;
  dimensionNumber: Int8 | null;
  dimensionType: string | null;
  hypertableName: string | null;
  hypertableSchema: string | null;
  integerInterval: Int8 | null;
  integerNowFunc: string | null;
  numPartitions: number | null;
  timeInterval: Interval | null;
}

export interface TimescaledbInformationHypertableColumnstoreSettings {
  compressIntervalLength: string | null;
  hypertable: string | null;
  orderby: string | null;
  segmentby: string | null;
}

export interface TimescaledbInformationHypertableCompressionSettings {
  compressIntervalLength: string | null;
  hypertable: string | null;
  orderby: string | null;
  segmentby: string | null;
}

export interface TimescaledbInformationHypertables {
  compressionEnabled: boolean | null;
  hypertableName: string | null;
  hypertableSchema: string | null;
  numChunks: Int8 | null;
  numDimensions: number | null;
  owner: string | null;
  tablespaces: string[] | null;
}

export interface TimescaledbInformationJobErrors {
  errMessage: string | null;
  finishTime: Timestamp | null;
  jobId: number | null;
  pid: number | null;
  procName: string | null;
  procSchema: string | null;
  sqlerrcode: string | null;
  startTime: Timestamp | null;
}

export interface TimescaledbInformationJobHistory {
  config: Json | null;
  errMessage: string | null;
  finishTime: Timestamp | null;
  id: Int8 | null;
  jobId: number | null;
  pid: number | null;
  procName: string | null;
  procSchema: string | null;
  sqlerrcode: string | null;
  startTime: Timestamp | null;
  succeeded: boolean | null;
}

export interface TimescaledbInformationJobs {
  applicationName: string | null;
  checkName: string | null;
  checkSchema: string | null;
  config: Json | null;
  fixedSchedule: boolean | null;
  hypertableName: string | null;
  hypertableSchema: string | null;
  initialStart: Timestamp | null;
  jobId: number | null;
  maxRetries: number | null;
  maxRuntime: Interval | null;
  nextStart: Timestamp | null;
  owner: string | null;
  procName: string | null;
  procSchema: string | null;
  retryPeriod: Interval | null;
  scheduled: boolean | null;
  scheduleInterval: Interval | null;
}

export interface TimescaledbInformationJobStats {
  hypertableName: string | null;
  hypertableSchema: string | null;
  jobId: number | null;
  jobStatus: string | null;
  lastRunDuration: Interval | null;
  lastRunStartedAt: Timestamp | null;
  lastRunStatus: string | null;
  lastSuccessfulFinish: Timestamp | null;
  nextStart: Timestamp | null;
  totalFailures: Int8 | null;
  totalRuns: Int8 | null;
  totalSuccesses: Int8 | null;
}

export interface Users {
  profilePictureUrl: string;
  suiAddress: string;
  username: string;
}

export interface DB {
  "_TimescaledbCatalog.chunk": _TimescaledbCatalogChunk;
  "_TimescaledbCatalog.chunkColumnStats": _TimescaledbCatalogChunkColumnStats;
  "_TimescaledbCatalog.chunkConstraint": _TimescaledbCatalogChunkConstraint;
  "_TimescaledbCatalog.chunkIndex": _TimescaledbCatalogChunkIndex;
  "_TimescaledbCatalog.compressionAlgorithm": _TimescaledbCatalogCompressionAlgorithm;
  "_TimescaledbCatalog.compressionChunkSize": _TimescaledbCatalogCompressionChunkSize;
  "_TimescaledbCatalog.compressionSettings": _TimescaledbCatalogCompressionSettings;
  "_TimescaledbCatalog.continuousAgg": _TimescaledbCatalogContinuousAgg;
  "_TimescaledbCatalog.continuousAggMigratePlan": _TimescaledbCatalogContinuousAggMigratePlan;
  "_TimescaledbCatalog.continuousAggMigratePlanStep": _TimescaledbCatalogContinuousAggMigratePlanStep;
  "_TimescaledbCatalog.continuousAggsBucketFunction": _TimescaledbCatalogContinuousAggsBucketFunction;
  "_TimescaledbCatalog.continuousAggsHypertableInvalidationLog": _TimescaledbCatalogContinuousAggsHypertableInvalidationLog;
  "_TimescaledbCatalog.continuousAggsInvalidationThreshold": _TimescaledbCatalogContinuousAggsInvalidationThreshold;
  "_TimescaledbCatalog.continuousAggsMaterializationInvalidationLog": _TimescaledbCatalogContinuousAggsMaterializationInvalidationLog;
  "_TimescaledbCatalog.continuousAggsWatermark": _TimescaledbCatalogContinuousAggsWatermark;
  "_TimescaledbCatalog.dimension": _TimescaledbCatalogDimension;
  "_TimescaledbCatalog.dimensionSlice": _TimescaledbCatalogDimensionSlice;
  "_TimescaledbCatalog.hypertable": _TimescaledbCatalogHypertable;
  "_TimescaledbCatalog.metadata": _TimescaledbCatalogMetadata;
  "_TimescaledbCatalog.tablespace": _TimescaledbCatalogTablespace;
  "_TimescaledbCatalog.telemetryEvent": _TimescaledbCatalogTelemetryEvent;
  "_TimescaledbConfig.bgwJob": _TimescaledbConfigBgwJob;
  "_TimescaledbInternal.bgwJobStat": _TimescaledbInternalBgwJobStat;
  "_TimescaledbInternal.bgwJobStatHistory": _TimescaledbInternalBgwJobStatHistory;
  "_TimescaledbInternal.bgwPolicyChunkStats": _TimescaledbInternalBgwPolicyChunkStats;
  "_TimescaledbInternal.compressedChunkStats": _TimescaledbInternalCompressedChunkStats;
  "_TimescaledbInternal.hypertableChunkLocalSize": _TimescaledbInternalHypertableChunkLocalSize;
  bondingCurve: BondingCurve;
  coins: Coins;
  comments: Comments;
  cursors: Cursors;
  images: Images;
  likes: Likes;
  posts: Posts;
  rawPrices: RawPrices;
  "timescaledbExperimental.policies": TimescaledbExperimentalPolicies;
  "timescaledbInformation.chunkColumnstoreSettings": TimescaledbInformationChunkColumnstoreSettings;
  "timescaledbInformation.chunkCompressionSettings": TimescaledbInformationChunkCompressionSettings;
  "timescaledbInformation.chunks": TimescaledbInformationChunks;
  "timescaledbInformation.compressionSettings": TimescaledbInformationCompressionSettings;
  "timescaledbInformation.continuousAggregates": TimescaledbInformationContinuousAggregates;
  "timescaledbInformation.dimensions": TimescaledbInformationDimensions;
  "timescaledbInformation.hypertableColumnstoreSettings": TimescaledbInformationHypertableColumnstoreSettings;
  "timescaledbInformation.hypertableCompressionSettings": TimescaledbInformationHypertableCompressionSettings;
  "timescaledbInformation.hypertables": TimescaledbInformationHypertables;
  "timescaledbInformation.jobErrors": TimescaledbInformationJobErrors;
  "timescaledbInformation.jobHistory": TimescaledbInformationJobHistory;
  "timescaledbInformation.jobs": TimescaledbInformationJobs;
  "timescaledbInformation.jobStats": TimescaledbInformationJobStats;
  users: Users;
}
